Repository junxtar/spring-newsfeed, pull requests merged in 2023-11, with the labels that each got.

#1 JasyptConfig 파일 설정 구현
  build.gradle
  src/main/java/com/sparta/springnewsfeed/global/config/JasyptConfig.java
  src/main/resources/application.properties
  src/main/resources/application.yml
  src/test/java/com/sparta/springnewsfeed/jasypt/JasyptTest.java
Labels: feat, chore

#4 feat: JWT 및 시큐리티 세팅
  build.gradle
  src/main/java/com/sparta/springnewsfeed/domain/user/controller/UserController.java
  src/main/java/com/sparta/springnewsfeed/domain/user/dto/UserLoginRequestDto.java
  src/main/java/com/sparta/springnewsfeed/domain/user/dto/UserSignupRequestDto.java
  src/main/java/com/sparta/springnewsfeed/domain/user/entity/User.java
  src/main/java/com/sparta/springnewsfeed/domain/user/repository/UserRepository.java
  src/main/java/com/sparta/springnewsfeed/domain/user/service/UserService.java
  src/main/java/com/sparta/springnewsfeed/global/common/CommonCode.java
  src/main/java/com/sparta/springnewsfeed/global/config/WebSecurityConfig.java
  src/main/java/com/sparta/springnewsfeed/global/jwt/JwtUtil.java
  src/main/java/com/sparta/springnewsfeed/global/security/JwtAuthenticationFilter.java
  src/main/java/com/sparta/springnewsfeed/global/security/JwtAuthorizationFilter.java
  src/main/java/com/sparta/springnewsfeed/global/security/UserDetailsImpl.java
  src/main/java/com/sparta/springnewsfeed/global/security/UserDetailsServiceImpl.java
Labels: feat

#6 feat: Post 구현
  src/main/java/com/sparta/springnewsfeed/domain/post/controller/PostController.java
  src/main/java/com/sparta/springnewsfeed/domain/post/dto/PostRequestDto.java
  src/main/java/com/sparta/springnewsfeed/domain/post/dto/PostResponseDto.java
  src/main/java/com/sparta/springnewsfeed/domain/post/entity/Post.java
  src/main/java/com/sparta/springnewsfeed/domain/post/entity/Time.java
  src/main/java/com/sparta/springnewsfeed/domain/post/repository/PostRepository.java
  src/main/java/com/sparta/springnewsfeed/domain/post/service/PostService.java
Labels: feat

#8 feat: Time -> BaseTime 변경 AuditingConfig.java 추가&적용
  src/main/java/com/sparta/springnewsfeed/domain/post/entity/Post.java
  src/main/java/com/sparta/springnewsfeed/global/config/AuditingConfig.java
  src/main/java/com/sparta/springnewsfeed/global/util/BaseTime.java
Labels: feat

#9 docs: post
  src/main/java/com/sparta/springnewsfeed/domain/post/controller/PostController.java
  src/main/java/com/sparta/springnewsfeed/domain/post/dto/PostResponseDto.java
  src/main/java/com/sparta/springnewsfeed/domain/post/entity/Post.java
  src/main/java/com/sparta/springnewsfeed/domain/post/service/PostService.java
Labels: feat

#11 refactor : 연관 관계 수정
  src/main/java/com/sparta/springnewsfeed/domain/post/entity/Post.java
  src/main/java/com/sparta/springnewsfeed/domain/post/service/PostService.java
Labels: refactor

#16 Feat/error handle
  src/main/java/com/sparta/springnewsfeed/domain/post/exception/PostErrorCode.java
  src/main/java/com/sparta/springnewsfeed/domain/post/exception/PostExistsException.java
  src/main/java/com/sparta/springnewsfeed/domain/post/service/PostService.java
  src/main/java/com/sparta/springnewsfeed/domain/user/dto/UserSignupRequestDto.java
  src/main/java/com/sparta/springnewsfeed/global/common/CommonCode.java
  src/main/java/com/sparta/springnewsfeed/global/common/CommonErrorCode.java
  src/main/java/com/sparta/springnewsfeed/global/exception/ErrorCode.java
  src/main/java/com/sparta/springnewsfeed/global/exception/RestApiException.java
  src/main/java/com/sparta/springnewsfeed/global/exception/advice/GlobalExceptionHandler.java
  src/main/java/com/sparta/springnewsfeed/global/exception/response/ErrorResponse.java
Labels: feat, refactor

#18 feat: Post에 댓글목록 구현시키기
  src/main/java/com/sparta/springnewsfeed/domain/post/controller/PostController.java
  src/main/java/com/sparta/springnewsfeed/domain/post/dto/SelectPostResponseDto.java
  src/main/java/com/sparta/springnewsfeed/domain/post/entity/Post.java
  src/main/java/com/sparta/springnewsfeed/domain/post/service/PostService.java
  src/main/java/com/sparta/springnewsfeed/domain/user/entity/User.java
Labels: feat

#21 #20 feat: Comment 수정 완료
  src/main/java/com/sparta/springnewsfeed/domain/comment/controller/CommentController.java
  src/main/java/com/sparta/springnewsfeed/domain/comment/entity/Comment.java
  src/main/java/com/sparta/springnewsfeed/domain/comment/repository/CommentRepository.java
  src/main/java/com/sparta/springnewsfeed/domain/comment/service/CommentService.java
Labels: feat

#26 docs: Post에러코드명 변경
  src/main/java/com/sparta/springnewsfeed/domain/post/exception/PostErrorCode.java
  src/main/java/com/sparta/springnewsfeed/domain/post/service/PostService.java
Labels: feat

#28 refactor : RequestParam 을 PathVariable 로 변경,
  src/main/java/com/sparta/springnewsfeed/domain/comment/controller/CommentController.java
  src/main/java/com/sparta/springnewsfeed/domain/comment/service/CommentService.java
Labels: refactor

#29 #23 refactor : Comment Delete Api 변경
  src/main/java/com/sparta/springnewsfeed/domain/comment/controller/CommentController.java
Labels: refactor

#32 feat: 비밀번호 수정 구현 / Custom 에러 수정
  src/main/java/com/sparta/springnewsfeed/domain/user/controller/UserController.java
  src/main/java/com/sparta/springnewsfeed/domain/user/dto/UserModifyPasswordRequestDto.java
  src/main/java/com/sparta/springnewsfeed/domain/user/dto/UserModifyPasswordResponse.java
  src/main/java/com/sparta/springnewsfeed/domain/user/dto/UserSignupRequestDto.java
  src/main/java/com/sparta/springnewsfeed/domain/user/entity/User.java
  src/main/java/com/sparta/springnewsfeed/domain/user/exception/AlreadyExistUserException.java
  src/main/java/com/sparta/springnewsfeed/domain/user/exception/NonUserExsistException.java
  src/main/java/com/sparta/springnewsfeed/domain/user/exception/PasswordIsNotMatchException.java
  src/main/java/com/sparta/springnewsfeed/domain/user/exception/UserErrorCode.java
  src/main/java/com/sparta/springnewsfeed/domain/user/service/UserService.java
  src/main/java/com/sparta/springnewsfeed/global/config/WebSecurityConfig.java
Labels: feat

#34 Feat/logout
  src/main/java/com/sparta/springnewsfeed/domain/user/controller/UserController.java
  src/main/java/com/sparta/springnewsfeed/domain/user/dto/UserLoginRequestDto.java
  src/main/java/com/sparta/springnewsfeed/domain/user/dto/UserModifyPasswordRequestDto.java
  src/main/java/com/sparta/springnewsfeed/domain/user/dto/UserModifyPasswordResponse.java
  src/main/java/com/sparta/springnewsfeed/domain/user/dto/UserResponseDto.java
  src/main/java/com/sparta/springnewsfeed/domain/user/dto/UserSignupRequestDto.java
  src/main/java/com/sparta/springnewsfeed/domain/user/dto/UserUpdateProfileRequestDto.java
  src/main/java/com/sparta/springnewsfeed/domain/user/entity/User.java
  src/main/java/com/sparta/springnewsfeed/domain/user/service/UserService.java
  src/main/java/com/sparta/springnewsfeed/global/config/WebSecurityConfig.java
  src/main/java/com/sparta/springnewsfeed/global/redis/RedisUtil.java
  src/main/java/com/sparta/springnewsfeed/global/security/UserDetailsServiceImpl.java
Labels: feat, style, refactor

#30 feat: 게시글 좋아요 기능 구현하기
  src/main/java/com/sparta/springnewsfeed/domain/heart/Heart.java
  src/main/java/com/sparta/springnewsfeed/domain/heart/HeartController.java
  src/main/java/com/sparta/springnewsfeed/domain/heart/HeartRepository.java
  src/main/java/com/sparta/springnewsfeed/domain/heart/HeartService.java
  src/main/java/com/sparta/springnewsfeed/domain/post/constant/PostConstant.java
  src/main/java/com/sparta/springnewsfeed/domain/post/controller/PostController.java
  src/main/java/com/sparta/springnewsfeed/domain/post/dto/SelectPostResponseDto.java
  src/main/java/com/sparta/springnewsfeed/domain/post/entity/Post.java
  src/main/java/com/sparta/springnewsfeed/domain/post/service/PostService.java
Labels: feat

#35 Refactor/heart like
  src/main/java/com/sparta/springnewsfeed/domain/comment/entity/Comment.java
  src/main/java/com/sparta/springnewsfeed/domain/heart/HeartController.java
  src/main/java/com/sparta/springnewsfeed/domain/heart/HeartService.java
  src/main/java/com/sparta/springnewsfeed/domain/heart/constant/HeartConstant.java
  src/main/java/com/sparta/springnewsfeed/domain/heart/controller/HeartController.java
  src/main/java/com/sparta/springnewsfeed/domain/heart/dto/ResponseHeartDto.java
  src/main/java/com/sparta/springnewsfeed/domain/heart/entity/Heart.java
  src/main/java/com/sparta/springnewsfeed/domain/heart/repository/HeartRepository.java
  src/main/java/com/sparta/springnewsfeed/domain/heart/service/HeartService.java
  src/main/java/com/sparta/springnewsfeed/domain/post/dto/SelectPostResponseDto.java
  src/main/java/com/sparta/springnewsfeed/domain/post/entity/Post.java
  src/main/java/com/sparta/springnewsfeed/domain/redis/RedisConfig.java
  src/main/java/com/sparta/springnewsfeed/domain/redis/RedisUtil.java
  src/main/java/com/sparta/springnewsfeed/domain/user/service/UserService.java
  src/main/java/com/sparta/springnewsfeed/domain/utils/BaseTime.java
  src/main/java/com/sparta/springnewsfeed/global/config/WebSecurityConfig.java
  src/main/java/com/sparta/springnewsfeed/global/security/JwtAuthenticationFilter.java
  src/main/java/com/sparta/springnewsfeed/global/security/JwtAuthorizationFilter.java
Labels: feat, style, refactor, chore

#36 refactor: 게시물 조회시 좋아요 갯수 및 좋아요 여부 조회 추가
  src/main/java/com/sparta/springnewsfeed/domain/post/controller/PostController.java
  src/main/java/com/sparta/springnewsfeed/domain/post/dto/PostMyResponseDto.java
  src/main/java/com/sparta/springnewsfeed/domain/post/dto/PostResponseDto.java
  src/main/java/com/sparta/springnewsfeed/domain/post/dto/SelectPostResponseDto.java
  src/main/java/com/sparta/springnewsfeed/domain/post/dto/UsersPostResponseDto.java
  src/main/java/com/sparta/springnewsfeed/domain/post/service/PostService.java
Labels: refactor

#38 Feat/comment likes
  src/main/java/com/sparta/springnewsfeed/domain/comment/constant/CommentConstant.java
  src/main/java/com/sparta/springnewsfeed/domain/comment/controller/CommentController.java
  src/main/java/com/sparta/springnewsfeed/domain/comment/dto/CommentResponseDto.java
  src/main/java/com/sparta/springnewsfeed/domain/comment/entity/Comment.java
  src/main/java/com/sparta/springnewsfeed/domain/comment/exception/CommentErrorCode.java
  src/main/java/com/sparta/springnewsfeed/domain/comment/service/CommentService.java
  src/main/java/com/sparta/springnewsfeed/domain/commentLike/Constant/LikeConstant.java
  src/main/java/com/sparta/springnewsfeed/domain/commentLike/controller/LikeController.java
  src/main/java/com/sparta/springnewsfeed/domain/commentLike/dto/LikeResponseDto.java
  src/main/java/com/sparta/springnewsfeed/domain/commentLike/entity/Likes.java
  src/main/java/com/sparta/springnewsfeed/domain/commentLike/repository/LikeRepository.java
  src/main/java/com/sparta/springnewsfeed/domain/commentLike/service/LikeService.java
Labels: feat, refactor

#40 refactor: HeartService에서 PostRepository 대신 PostService 사용하기
  src/main/java/com/sparta/springnewsfeed/domain/heart/service/HeartService.java
  src/main/java/com/sparta/springnewsfeed/domain/post/service/PostService.java
Labels: refactor
